package:
  name: mariadb-connector-c
  version: 3.0.2

source:
  url: https://downloads.mariadb.com/Connectors/c/connector-c-3.0.2/mariadb-connector-c-3.0.2-src.tar.gz
  md5: 2eb5ba004ac105eebb538ead352c0c78
  sha1: bc1fd6c20610822abdb67fe300bd723fe9225e50
  sha256: 518d14b8d77838370767d73f9bf1674f46232e1a2a34d4195bd38f52a3033758

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.

requirements:
  build:
    - toolchain
    - cmake
    - ninja
    - openssl 1.0.*
  run:
    - openssl 1.0.*
